In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('movies_metadata.csv')

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 38.8+ MB

In [6]:
df.shape

(45466, 24)

In [7]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(13)

In [9]:
df = df.drop_duplicates().reset_index(drop=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df[['title', 'genres', 'overview', 'vote_average', 'vote_count', 'popularity' , 'tagline']]

In [12]:
df

,title,genres,overview,vote_average,vote_count,popularity,tagline
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,NaN
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,Roll the dice and unleash the excitement!
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Friends are the people who let you be yourself...
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Just When His World Is Back To Normal... He's ...
...,...,...,...,...,...,...,...
45448,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman.,4.0,1.0,0.072051,Rising and falling between a man and woman
45449,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,9.0,3.0,0.178241,NaN
45450,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",3.8,6.0,0.903007,A deadly game of wits.
45451,Satan Triumphant,[],"In a small town live two brothers, one a minis...",0.0,0.0,0.003503,NaN
45452,Queerama,[],50 years after decriminalisation of homosexual...,0.0,0.0,0.163015,NaN

In [13]:
df.isnull().sum()

title               6
genres              0
overview          954
vote_average        6
vote_count          6
popularity          5
tagline         25045
dtype: int64

In [14]:
df = df.dropna(subset=['title'])

In [15]:
df['overview'] = df['overview'].fillna('')

In [16]:
df

,title,genres,overview,vote_average,vote_count,popularity,tagline
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,NaN
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,Roll the dice and unleash the excitement!
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Friends are the people who let you be yourself...
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Just When His World Is Back To Normal... He's ...
...,...,...,...,...,...,...,...
45448,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman.,4.0,1.0,0.072051,Rising and falling between a man and woman
45449,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,9.0,3.0,0.178241,NaN
45450,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",3.8,6.0,0.903007,A deadly game of wits.
45451,Satan Triumphant,[],"In a small town live two brothers, one a minis...",0.0,0.0,0.003503,NaN
45452,Queerama,[],50 years after decriminalisation of homosexual...,0.0,0.0,0.163015,NaN

In [17]:
df.iloc[0]['genres']
import ast

In [18]:
df['genres'] = df['genres'].apply(lambda x: "".join([i['name'] for i in ast.literal_eval(x)]))

In [19]:
df.head()

,title,genres,overview,vote_average,vote_count,popularity,tagline
0,Toy Story,AnimationComedyFamily,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,NaN
1,Jumanji,AdventureFantasyFamily,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,Roll the dice and unleash the excitement!
2,Grumpier Old Men,RomanceComedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,ComedyDramaRomance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Friends are the people who let you be yourself...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Just When His World Is Back To Normal... He's ...

In [20]:
df['tagline'] = df['tagline'].fillna('')

In [21]:
df.isnull().sum()

title           0
genres          0
overview        0
vote_average    0
vote_count      0
popularity      0
tagline         0
dtype: int64

In [22]:
df['tags'] = df['overview'] + df['genres'] + df['tagline']

In [23]:
df.head()

,title,genres,overview,vote_average,vote_count,popularity,tagline,tags
0,Toy Story,AnimationComedyFamily,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,AdventureFantasyFamily,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,RomanceComedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,ComedyDramaRomance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...

NLP

In [24]:
df['tags'] [1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.AdventureFantasyFamilyRoll the dice and unleash the excitement!"

In [25]:
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer      
import re

In [26]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Error loading stopwords: <urlopen error pathsec.urlopen:
[nltk_data]     no validated address for host
[nltk_data]     'raw.githubusercontent.com'; refusing to connect by
[nltk_data]     unvalidated hostname>
[nltk_data] Error loading wordnet: <urlopen error pathsec.urlopen: no
[nltk_data]     validated address for host
[nltk_data]     'raw.githubusercontent.com'; refusing to connect by
[nltk_data]     unvalidated hostname>

False

In [27]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [28]:

def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stopwords]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [29]:
df['tags'] = df['tags'].apply(preprocess_text)

In [30]:
df.head()

,title,genres,overview,vote_average,vote_count,popularity,tagline,tags
0,Toy Story,AnimationComedyFamily,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,,led woody andys toy live happily room andys bi...
1,Jumanji,AdventureFantasyFamily,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,Roll the dice and unleash the excitement!,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,RomanceComedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Still Yelling. Still Fighting. Still Ready for...,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,ComedyDramaRomance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Friends are the people who let you be yourself...,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Just When His World Is Back To Normal... He's ...,george bank recovered daughter wedding receive...

In [31]:
df['tags'] [1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creaturesadventurefantasyfamilyroll dice unleash excitement'

    vectorization

In [32]:
df= df.reset_index( drop=True )

In [33]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1, 2), stop_words='english')

In [36]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [37]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1351319 stored elements and shape (45447, 50000)>

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [41]:
def recommend(title, n=10): 
    if title not in indices:
        return "Movie not found in the dataset."    
    idx = indices[title]
    sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    sim_idx = sim_scores.argsort()[::-1][1:n+1]
    return df['title'].iloc[sim_idx].tolist()

In [45]:
recommend('Avenger')

['The Hunting Party',
 'Hopscotch',
 'Tough and Deadly',
 'Sharpshooter',
 'Hit by Lightning',
 "Dexter's Laboratory: Ego Trip",
 'Deceptive Practice: The Mysteries and Mentors of Ricky Jay',
 'The Escapist',
 'The Man Nobody Knew: In Search of My Father, CIA Spymaster William Colby',
 'Silent Night, Deadly Night II']

In [48]:
import pickle 

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))